// script.js

// Dati iniziali const startButton = document.getElementById("startGame"); const overlay = document.getElementById("overlay"); const xpDisplay = document.getElementById("xp"); const xpNextDisplay = document.getElementById("xpNext"); const levelDisplay = document.getElementById("level"); const materialDisplay = document.getElementById("material"); const energyDisplay = document.getElementById("energy"); const dayDisplay = document.getElementById("currentDay"); const roomButtons = document.querySelectorAll(".room"); const actionsPanel = document.getElementById("actionsPanel"); const actionsList = document.getElementById("actionsList"); const roomTitle = document.getElementById("roomTitle"); const closeActions = document.getElementById("closeActions");

let xp = parseInt(localStorage.getItem("xp")) || 0; let level = parseInt(localStorage.getItem("level")) || 1; let energy = parseInt(localStorage.getItem("energy")) || 100; let currentDay = parseInt(localStorage.getItem("day")) || 1; let xpNext = level * 100; const maxEnergy = 100;

const materials = [ "Polvere", "Bronzo", "Argento", "Oro", "Diamante", "Iridio", "Platino", "Titanio", "Neon", "Ethereo" ];

// Azioni per stanza (semplificate per ora, verranno ampliate) const actions = { studio: [ { name: "Leggere un libro", xp: 10, energy: 5 }, { name: "Scrivere un appunto", xp: 5, energy: 3 }, { name: "Risolvere un problema", xp: 15, energy: 10 }, { name: "Pianificare la settimana", xp: 8, energy: 4 }, { name: "Rivedere appunti", xp: 6, energy: 4 }, { name: "Meditazione rapida", xp: 4, energy: -5 }, { name: "Bere acqua", xp: 0, energy: -10 } ], lavoro: [ { name: "Scrivere email", xp: 8, energy: 6 }, { name: "Completare attività", xp: 20, energy: 15 }, { name: "Organizzare documenti", xp: 10, energy: 7 } ], pulizie: [ { name: "Lavare piatti", xp: 5, energy: 5 }, { name: "Spazzare il pavimento", xp: 7, energy: 6 } ], creatività: [ { name: "Disegnare", xp: 12, energy: 8 }, { name: "Scrivere una poesia", xp: 10, energy: 7 } ], apprendimento: [ { name: "Guardare un documentario", xp: 12, energy: 6 }, { name: "Seguire un corso online", xp: 15, energy: 10 } ], finanze: [ { name: "Registrare una spesa", xp: 3, energy: 2 }, { name: "Aggiungere un'entrata", xp: 4,
